version: '3.8'

services:
  ollama-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: xsukax-ollama-webui:latest
    container_name: ollama-webui
    ports:
      - "3553:80"
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - ollama-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.docker.compose.project=ollama-webui"
      - "com.docker.compose.service=frontend"
      - "traefik.enable=false"  # Disable if using Traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits (optional - uncomment if needed)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 256M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 128M

networks:
  ollama-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Optional: Add volumes for persistent data or custom configurations
# volumes:
#   nginx-cache:
#     driver: local